version: '3.8'

services:

  postgres:
    container_name: postgres
    image: postgres:13-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=junuser
      - POSTGRES_PASSWORD=junpwd
      - POSTGRES_DB=jundb
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    restart: always

  adminer:
    container_name: adminer
    image: adminer:latest
    links:
      - postgres
    ports:
      - 8081:8080
    restart: always

volumes:
  postgres-volume: