POSTGRES_URL: jdbc:postgresql://35.241.209.158:5432/junction
POSTGRES_USER: postgres
POSTGRES_PASSWORD: asdasd

---

server:
  port: 12345

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: ${POSTGRES_URL}
    driverClassName: org.postgresql.Driver
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    hikari:
      autoCommit: false
      cachePrepStmts: true
      useServerPrepStmts: true
  jpa:
    generate-ddl: true
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect
  hibernate:
    ddl-auto: update